### ISSUE TITLE
need teacher.pkl

### ISSUE THREAD

**Issue by nbbllxx0** [Errno1024/SRKT-ntire2021#2]
thanks for your great work! i would like to re-train your network as one of my baseline for comparing methods,would you plz add teacher.pkl in your code? that will be of great help

**Comment by Errno1024** [comment]
Sorry my teacher.pkl is deleted, but you can train the teacher network using train.py. Just add -t in your command line to switch the code to teacher training mode. Hopefully this would help you.

**Comment by nbbllxx0** [comment]
> Sorry my teacher.pkl is deleted, but you can train the teacher network using train.py. Just add -t in your command line to switch the code to teacher training mode. Hopefully this would help you.

it seems the trained teacher.pkl on our dataset could not match the keys with 'model_teacher.pkl' needed, the stored model_kt_sr_XXX.pkl in ./checkpoints with '-t' in command could not be just namechanged to 'model_teacher.pkl' for training

**Comment by Errno1024** [comment]
I checked the code and found a bug. When saving the checkpoint file, the data is wrapped by a dict with key "model", but it is not unwrapped when loading the checkpoint. The bug is now fixed.

**Comment by nbbllxx0** [comment]
> I checked the code and found a bug. When saving the checkpoint file, the data is wrapped by a dict with key "model", but it is not unwrapped when loading the checkpoint. The bug is now fixed.

thanks for your reply, on it
